# Generated by Django 5.2.3 on 2025-06-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('employee_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Employee Number')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('available_hours_per_week', models.DecimalField(decimal_places=2, default=40.0, max_digits=4, verbose_name='Available Hours per Week')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Professional Profile Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('counts_towards_staff_ratio', models.BooleanField(default=False, verbose_name='Counts towards Staff Ratio')),
            ],
            options={
                'verbose_name': 'Professional Profile',
                'verbose_name_plural': 'Professional Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Qualification Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Is Critical (e.g., Ventilation Certificate)')),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ward Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('min_staff_early_shift', models.IntegerField(default=1, verbose_name='Min. Staff Early Shift')),
                ('min_staff_late_shift', models.IntegerField(default=1, verbose_name='Min. Staff Late Shift')),
                ('min_staff_night_shift', models.IntegerField(default=1, verbose_name='Min. Staff Night Shift')),
                ('current_patients', models.IntegerField(default=0, verbose_name='Current Number of Patients')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('type', models.CharField(choices=[('VACATION', 'Vacation'), ('SICKNESS', 'Sickness'), ('TRAINING', 'Training'), ('OTHER', 'Other')], max_length=20, null=True, verbose_name='Absence Type')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_planer.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['start_date', 'employee'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='professional_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shift_planer.professionalprofile', verbose_name='Professional Profile'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='shift_planer.qualification', verbose_name='Qualifications'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EARLY', 'Early Shift'), ('LATE', 'Late Shift'), ('NIGHT', 'Night Shift'), ('OTHER', 'Other Shift')], max_length=50, unique=True, verbose_name='Shift Type')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('required_qualifications', models.ManyToManyField(blank=True, to='shift_planer.qualification', verbose_name='Required Qualifications')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='allowed_shifts',
            field=models.ManyToManyField(blank=True, related_name='allowed_employees', to='shift_planer.shift', verbose_name='Allowed Shifts'),
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_planer.employee', verbose_name='Employee')),
                ('preferred_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shift_planer.shift', verbose_name='Preferred Shift')),
            ],
            options={
                'verbose_name': 'Employee Availability',
                'verbose_name_plural': 'Employee Availabilities',
                'ordering': ['date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('CONFIRMED', 'Confirmed'), ('CONFLICT', 'Conflict'), ('UNASSIGNED', 'Unassigned / Open')], default='UNASSIGNED', max_length=20, verbose_name='Status')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_planer.employee', verbose_name='Employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_planer.shift', verbose_name='Shift')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_planer.ward', verbose_name='Ward')),
            ],
            options={
                'verbose_name': 'Shift Assignment',
                'verbose_name_plural': 'Shift Assignments',
                'ordering': ['date', 'ward', 'shift__start_time'],
                'unique_together': {('date', 'shift', 'employee')},
            },
        ),
    ]
